name: mautic_api
description: Dart and Flutter Package Wrapper for Native Mautic REST API using Basic Authentication
version: 1.0.7
homepage: https://github.com/powerticmkt/dart-mautic-api

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  crypto: ^2.1.4
  http: ^0.12.0+4
  meta: ^1.1.8
  convert: ^2.1.1
